In [529]:
import pandas as pd

In [530]:
# Читання CSV файла з використанням стандартного декодування (UTF-8). 
# Попередньо файл завантажен в jupyter.
df = pd.read_csv ('survey_results_public.csv', encoding='utf-8', low_memory=False) 
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [531]:
# Показуємо структура Датасету
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [532]:
# Рахуємо пропуски в кожній колонці
df.isna().sum()

ResponseId                 0
MainBranch                 0
Age                        0
EdLevel                 1042
Employment               852
                       ...
AIAgentExtWrite        48332
AIHuman                19997
AIOpen                 26651
ConvertedCompYearly    25244
JobSat                 22521
Length: 172, dtype: int64

In [533]:
# Сортуємо колонки за кількістю пропусків. Показуємо 20 найпроблемніших колонок
df.isna().sum().sort_values(ascending=False).head(20)

AIAgentObsWrite         48927
SOTagsWant Entry        48761
SOTagsHaveEntry         48733
AIModelsWantEntry       48716
AIAgentOrchWrite        48713
JobSatPoints_15_TEXT    48527
AIAgentKnowWrite        48425
AIModelsHaveEntry       48415
SO_Actions_15_TEXT      48368
AIAgentExtWrite         48332
CommPlatformWantEntr    48007
CommPlatformHaveEntr    47715
DatabaseWantEntry       47658
OfficeStackWantEntry    47574
TechOppose_15_TEXT      47544
TechEndorse_13_TEXT     47182
DevEnvWantEntry         47079
DatabaseHaveEntry       47041
OfficeStackHaveEntry    46602
WebframeWantEntry       46561
dtype: int64

In [534]:
# Читання CSV файл з використанням стандартного декодування (UTF-8). Попередньо файл завантажен в jupyter.
df1 = pd.read_csv ('survey_results_schema.csv', encoding='utf-8')
df1.head()

# Ознайомлення зі структурою файла
# Він містить: колонку з кодами питань і текстове пояснення, що означає кожний з цих кодів

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [535]:
# Налаштування параметрів для відображення всіх колонок у DataFrame.
pd.set_option('display.max_columns', None)

In [536]:
# DataFrame, опитування респондентів.
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [537]:
# DataFrame, з питаннями опитування.
df1

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

**Завдання 1. Підрахунок загальної кількості респондентів**

In [538]:
#    Використовуємо .nunique() - метод series, який пілраховує кількість унікальних значень у стовпці ResponseId.
total_respondents = df['ResponseId'].nunique()
print(f"Загальна кількість респондентів: {total_respondents}")

Загальна кількість респондентів: 49191

**Завдання 2. Аналіз повноти відповідей респондентів**

In [539]:
# Отримуємо список питань із schema
# колонка qname містить назви всіх питань. questions - створюємо множину назв питань, які присутні одночасно в qname та серед стовпців df.
# Використання set() та qname.unique() створює множину унікальних qname
questions = set(df1['qname'].unique())
# len(questions)
print(f"Загальна кількість унікальних питань: {len(questions)}")

Загальна кількість унікальних питань: 139

In [540]:
# Беремо лише ті питання, які реально є в основному датасеті:
# ми беремо перетин із df.columns, щоб отримати лише ті питання, які реально існують у датафреймі
questions_in_df = list(questions.intersection(set(df.columns)))
# len (questions_in_df)
print(f"Кількість питань, які реально є в основному датасеті: {len (questions_in_df)}")

Кількість питань, які реально є в основному датасеті: 126

In [541]:
# Видаляємо респондентів, у яких є пропуски хоча б в одному з цих питань
# dropna(): видаляє рядки, де є пропуски (NaN) у зазначених стовпцях.
answered_all = df[questions_in_df].dropna()

In [542]:
# Рахуємо кількість таких респондентів
# shape[0] повертає кількість рядків-тобто кількість респондентів, які відповіли на всі ці питання.
total_full_answers = answered_all.shape[0]

print(f"Кількість респондентів, які відповіли на всі ці питання: {total_full_answers}")

Кількість респондентів, які відповіли на всі ці питання: 0

**Завдання 3. Статистичний аналіз досвіду респондентів**

In [543]:
# Перевіримо тип даних
df['WorkExp'].head()
df['WorkExp'].dtype

dtype('float64')

In [544]:
# На всяк випадок-переконаємося, що колонка WorkExp числова:
df['WorkExp'] = pd.to_numeric(df['WorkExp'], errors='coerce')

In [545]:
# Рахуємо міри центральної тенденції
mean_exp = df['WorkExp'].mean()
median_exp = df['WorkExp'].median()
mode_exp = df['WorkExp'].mode()[0]   # беремо перше значення моди

In [546]:
# Гарно виводимо результат:
print("Міри центральної тенденції:")
print(f"Mean (середнє): {round(mean_exp, 1)} років")
print(f"Median (медіана): {round(median_exp, 1)} років")
print(f"Mode (мода): {mode_exp} років")

Міри центральної тенденції:
Mean (середнє): 13.4 років
Median (медіана): 10.0 років
Mode (мода): 10.0 років

In [547]:
# Візуалізуємо у вигляді таблиці:

# Рахуємо міри центральної тенденції
mean_exp = df['WorkExp'].mean()
median_exp = df['WorkExp'].median()
mode_exp = df['WorkExp'].mode()[0] 

# Формуємо таблицю
exp_stats_df = pd.DataFrame({
    'Metric': ['Mean (середнє)', 'Median (медіана)', 'Mode (мода)'],
    'Year': [round(mean_exp, 1), round(median_exp, 1), round(mode_exp, 1)]
})

# Робимо індекс 1, 2, 3
exp_stats_df.index = range(1, len(exp_stats_df) + 1)

print("Міри центральної тенденції:")
exp_stats_df

Міри центральної тенденції:

             Metric  Year
1    Mean (середнє)  13.4
2  Median (медіана)  10.0
3       Mode (мода)  10.0

**Завдання 4. Аналіз віддаленої роботи**

In [548]:
# Шукаемо потрібну колонку: Передивляємося всі назви колонок. Шукаємо щось пов’язане з форматом роботи:
df.columns.tolist()
# Похожа колонка: RemoteWork

['ResponseId',
 'MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_16',
 'JobSatPoints_15_TEXT',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvsHaveWorkedWith',
 'DevEnvsWantToWorkWith',
 'DevEnvsAdmired',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveWorkedWith',
 'SOTagsWantToWorkWith',
 'SOTagsAdmired',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen',
 'ConvertedCompYearly',
 'JobSat']

In [549]:
# Дивимося унікальні значення в підозрілій колонці:
df['RemoteWork'].value_counts(dropna=False)

RemoteWork
NaN                                                                             15411
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [550]:
# Фільтруємо тільки Remote
remote_workers = df[df['RemoteWork'] == 'Remote']

In [551]:
# Рахуємо кількість
num_remote = len(remote_workers)
print(f"Кількість віддалених працівників: {num_remote}")

Кількість віддалених працівників: 10931

**Завдання 5. Визначення популярності Python**

In [552]:
#Знаходимо правильну колонку
# У stack-overflow-developer-survey-2025 мови програмування повинні бути у колонці:
# LanguageHaveWorkedWith
# Дивимося, як виглядають значення:
df['LanguageHaveWorkedWith'].head (10)

0                     Bash/Shell (all shells);Dart;SQL
1                                                 Java
2                  Dart;HTML/CSS;JavaScript;TypeScript
3                                      Java;Kotlin;SQL
4    C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
5                                           Java;Scala
6                                JavaScript;TypeScript
7    Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
8                                    Java;Python;Scala
9                                                  NaN
Name: LanguageHaveWorkedWith, dtype: object

In [553]:
# Створюємо новий стовпець worked_with_python, який містить True/False, 
# де True означає, що респондент згадував Python у LanguageHaveWorkedWith.
# str.contains('...') - шукаємо слово 'python' 
# без урахування регістру та замінюємо пропуски (NaN) на False.
df['worked_with_python'] = ( 
    df['LanguageHaveWorkedWith']
    .str.contains('python', case=False, na=False)
)
df['worked_with_python'].head (10)

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
8     True
9    False
Name: worked_with_python, dtype: bool

In [554]:
# sum() - рахуємо загальну кількість респондентів, які працювали з Python.
python_devs = df['worked_with_python'].sum()
# python_devs
# виводимо результат:
print(f"Загальна кількість Python-розробників: {python_devs}")

Загальна кількість Python-розробників: 18466

In [555]:
# - обчислюємо частку таких респондентів у відсотках.
total_respondents = df.shape[0]
python_percent = (python_devs / total_respondents) * 100

In [556]:
# виводимо результат:
print(f"Відсоток респондентів, які програмують на Python: {python_percent:.1f}%")

Відсоток респондентів, які програмують на Python: 37.5%

**Завдання 6. Аналіз шляхів навчання програмуванню**

In [557]:
# Знаходимо колонку з навчанням:
#  це: LearnCode
# Превіряємо:
df['LearnCode'].head(10)

0    Online Courses or Certification (includes all ...
1    Online Courses or Certification (includes all ...
2    Online Courses or Certification (includes all ...
3    Other online resources (e.g. standard search, ...
4                                                  NaN
5    Online Courses or Certification (includes all ...
6    Videos (not associated with specific online co...
7    Books / Physical media;Technical documentation...
8    Online Courses or Certification (includes all ...
9    Other online resources (e.g. standard search, ...
Name: LearnCode, dtype: object

In [558]:
# Створюємо новий стовпець Learned_with_online_courses (True/False), 
# де True означає, що респондент навчався через онлайн-курси (Використовуємо стовпчик LearnCode)
df['Learned_with_online_courses'] = (
    df['LearnCode']
    .str.contains('online', case=False, na=False)
)
df['Learned_with_online_courses'].head(10)

0     True
1     True
2     True
3     True
4    False
5     True
6     True
7    False
8     True
9     True
Name: Learned_with_online_courses, dtype: bool

In [559]:
# Рахуємо кількість респондентів, які обрали онлайн курси.
online_learners = df['Learned_with_online_courses'].sum()
print(f"Кількість респондентів, що навчались через онлайн-курси: {online_learners}")
# Рахуємо відсоток (для кращої візуалізації)
percent_online = (online_learners / df.shape[0]) * 100
print(f"Це становить приблизно {percent_online:.1f}% від усіх респондентів")

Кількість респондентів, що навчались через онлайн-курси: 28352
Це становить приблизно 57.6% від усіх респондентів

**Завдання 7. Географічний аналіз компенсації Python-розробників**

In [560]:
# df.worked_with_python - відбираємо лише тих, хто працював з Python.
python_df = df[df['worked_with_python']].copy()

In [561]:
# Переконуємось, що зарплата числова
python_df['ConvertedCompYearly'] = pd.to_numeric(
    python_df['ConvertedCompYearly'], errors='coerce'
)
python_df['ConvertedCompYearly']

4        60000.0
7        72000.0
8        70000.0
15           NaN
17           NaN
          ...
49143        NaN
49145        NaN
49175        NaN
49176        NaN
49177        NaN
Name: ConvertedCompYearly, Length: 18466, dtype: float64

In [562]:
# Видаляємо рядки, де відсутнє значення зарплати (ConvertedCompYearly).
python_df = python_df.dropna(subset=['ConvertedCompYearly','Country'])

In [563]:
# .groupby() - групуємо дані за країною (Country)
# і обчислюємо середню (mean) та медіанну (median) зарплату для кожної країни.
# py_progers_by_country - таблиця з резульататами.
py_progers_by_country = (
    python_df.groupby('Country')['ConvertedCompYearly'] 
    .agg(['mean', 'median']).round (2) 
    .reset_index()
)
# Зробили назви колонок зрозумілими
py_progers_by_country.columns = [
    'Country',
    'Mean_Compensation_Yearly',
    'Median_Compensation_Yearly'
]
py_progers_by_country.head()

               Country  Mean_Compensation_Yearly  Median_Compensation_Yearly
0          Afghanistan                  22328.67                      1000.0
1              Albania                  47217.60                     50000.0
2              Algeria                  20187.29                      7088.0
3              Andorra                 226103.50                    226103.5
4  Antigua and Barbuda                      1.00                         1.0

**Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів**

In [564]:
# Вибираємо три стовпці: ResponseId, EdLevel, ConvertedCompYearly.
top5_education = (
    df[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]  
      .copy()
)
# Переконуємося, що зарплата - число.
top5_education['ConvertedCompYearly'] = pd.to_numeric(    
    top5_education['ConvertedCompYearly'], errors='coerce'
)
# Прибираємо пропуски зарплати, сортуємо у порядку спадання, оновлюємо індекс після сотрування.
# Відбираємо перші 5 рядків (топ-5 респондентів з найвищою зарплатою).
top5_education = (
    top5_education
      .dropna(subset=['ConvertedCompYearly'])              
      .sort_values(by='ConvertedCompYearly', ascending=False)  
      .reset_index(drop=True)                               
      .head(5)                                              
)
# Виводимо таблицю з 5 респондентами з найбільшою зарплатою і їх:
# ResponseId, EdLevel — рівень освіти, ConvertedCompYearly — річна компенсація
top5_education[['ResponseId', 'EdLevel', 'ConvertedCompYearly']]

,ResponseId,EdLevel,ConvertedCompYearly
0,34268,"Associate degree (A.A., A.S., etc.)",50000000.0
1,28701,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",33552715.0
2,43144,"Associate degree (A.A., A.S., etc.)",18387548.0
3,35354,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15430267.0
4,45972,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",13921760.0

**Завдання 9. Аналіз популярності Python по віковим категоріям**

In [565]:
# Беремо колонку з віком: Age
# Дивимося унікальні значення:
df['Age'].unique()

array(['25-34 years old', '35-44 years old', '45-54 years old',
       '18-24 years old', '65 years or older', '55-64 years old',
       'Prefer not to say'], dtype=object)

In [566]:
# Створюємо колонку "чи використовує Python"
df['UsesPython'] = df['LanguageHaveWorkedWith'].str.contains('Python', case=False, na=False)

In [567]:
python_by_age = (
    df.groupby('Age')['UsesPython'] # Групування по віку і розрахунок %
    .mean()
    .reset_index()
    .assign(PythonPercent = lambda x: (x['UsesPython'] * 100).round(1)) # Перевели у відсотки
    [['Age', 'PythonPercent']] # Залишаємо потрібні колонки
    .sort_values('PythonPercent', ascending=False) # Сортуємо та дивимось результат
)

python_by_age.head()

               Age  PythonPercent
0  18-24 years old           40.0
3  45-54 years old           38.6
4  55-64 years old           37.2
1  25-34 years old           36.9
2  35-44 years old           36.7

**Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників**

In [568]:
# Прибраємо пропуски в зарплаті
# Перцентиль рахується тільки по реальних значеннях.
comp_df = df.dropna(subset=['ConvertedCompYearly'])

In [569]:
# Обчислюємо 75-й перцентиль
# Це поріг: вище нього = високооплачувані
p75 = comp_df['ConvertedCompYearly'].quantile(0.75)
print(f"75-й перцентиль дорівнює:  {p75}")

75-й перцентиль дорівнює:  120596.0

In [570]:
# Відфільтрувуємо високооплачуваних
high_paid_df = comp_df[comp_df['ConvertedCompYearly'] > p75]

In [571]:
# Дивимося колонку RemoteWork
# Перевіряємо значення:
df['RemoteWork'].unique()

array(['Remote', 'Hybrid (some in-person, leans heavy to flexibility)',
       nan, 'In-person', 'Hybrid (some remote, leans heavy to in-person)',
       'Your choice (very flexible, you can come in when you want or just as needed)'],
      dtype=object)

In [572]:
# Віддалена робота містить текст: "Remote".
# Відфільтрувуємо тих, хто працює віддалено:
remote_high_paid_df = high_paid_df[
    high_paid_df['RemoteWork'].str.contains('Remote', na=False)
]
remote_high_paid_df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat,worked_with_python,Learned_with_online_courses,UsesPython
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,15.0,"Developer, mobile",500 to 999 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,9.0,3.0,4.0,8.0,11.0,7.0,5.0,1.0,10.0,14.0,NaN,12.0,4.0,5.0,9.0,14.0,7.0,11.0,6.0,2.0,15.0,NaN,Software Development,7.0,6.0,9.0,10.0,11.0,12.0,13.0,5.0,14.0,8.0,1.0,3.0,4.0,15.0,2.0,NaN,No,I have neither consider or transitioned into a...,6.0,6.0,United States of America,USD United States dollar,205000.0,Yes,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,NaN,NaN,NaN,NaN,Yes,MySQL;PostgreSQL;SQLite;Supabase,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,NaN,NaN,NaN,Yes,Next.js;Node.js;React,NaN,NaN,"Remix, Capacitor, Ionic",NaN,Yes,Android Studio;Claude Code;Cursor;IntelliJ IDE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;Linux (non-WSL),Windows;MacOS;Android;Linux (non-WSL),GitHub;GitLab;Google Workspace;Jira;Notion;Tre...,NaN,NaN,NaN,NaN,Discord;Reddit;Hacker News;GitHub (public proj...,NaN,NaN,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Between 10 and 15 years,"Infrequently, less than once per year",Chat (bot/AI),10.0,NaN,9.0,6.0,1.0,5.0,13.0,12.0,8.0,15.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Very poor at handling complex tasks,Writing code;Learning new concepts or technolo...,Project planning;Deployment and monitoring;Pre...,Learning about a codebase;Testing code,Committing and reviewing code;Creating or main...,Documenting code;Debugging or fixing code;Sear...,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0,False,True,False
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,23.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,11.0,10.0,9.0,8.0,2.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,2.0,3.0,4.0,11.0,12.0,5.0,6.0,10.0,7.0,8.0,9.0,13.0,14.0,15.0,1.0,NaN,No,I have neither consider or transitioned into a...,5.0,8.0,United States of America,USD United States dollar,250000.0,Yes,Elixir;HTML/CSS;JavaScript;SQL;TypeScript,Elixir;HTML/CSS;OCaml;Gleam,Elixir;HTML/CSS,NaN,NaN,Yes,BigQuery;Elasticsearch;PostgreSQL;SQLite,SQLite,SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Datadog;D...,Cloudflare;Homebrew;Make,Cloudflare;Homebrew;Make,hex,hex,Yes,Node.js;Phoenix;React,Phoenix,Phoenix,NaN,NaN,Yes,NaN,NaN,NaN,emacs,emacs,Tailwind CSS 4;Large Language Model,Tailwind CSS 4,Tailwind CSS 4,NaN,NaN,MacOS,MacOS,Airtable;Confluence;GitHub;Google Workspace;Ji...,NaN,NaN,NaN,NaN,Reddit;Dev.to;Hacker News;GitHub (public proje...,"GitHub (public projects, not private repos);Sl...","GitHub (public projects, not private repos);Sl...",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0,False,False,False
41,42,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Transitioning to retirement (gradually reducin...,25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training;Online Course...,25.0,"Developer, front-end",Less than 20 employees,Individual contributor,Remote,No,Personal Project,4.0,2.0,12.0,7.0,6.0,11.0,8.0,5.0,1.0,14.0,NaN,12.0,1.0,9.0,4.0,5.0,3.0,8.0,7.0,2.0,15.0,NaN,Software Development,5.0,2.0,6.0,11.0,10.0,8.0,7.0,9.0,12.0,13.0,1.0,14.0,3.0,15.0,4.0,NaN,Yes,I have somewhat considered changing my career ...,3.0,2.0,United States of America,USD United States dollar,270000.0,Yes,HTML/CSS;JavaScript;Python;TypeScript,HTML/CSS;JavaScript;Python;TypeScript,HTML/CSS;JavaScript;Python;TypeScript,NaN,NaN,Yes,PostgreSQL,PostgreSQL,PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Datadog;Homebrew;npm;Vercel;Vite,Datadog;Homebrew;npm;Vercel;Vite,NaN,NaN,Yes,Next.js;Node.js;React;Svelte,Svelte,Svelte,NaN,NaN,Yes,Cursor,Cursor,Cursor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS;iOS,MacOS;Linux (non-WSL),GitHub;Linear;Notion,GitHub;Linear;Notion,GitHub;Linear;Notion,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,Anthropic: Claude Sonnet,Anthropic: Claude Sonnet,Anthropic: Claude Sonnet,NaN,NaN,Yes,A few times per week,"More than 15 years, or since Stack Overflow st...",A few times per month or weekly,Chat (people);Job board,10.0,NaN,8.0,9.0,1.0,4.0,14.0,11.0,5.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Favorable,Somewhat distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Project planning;Committing and reviewing code...,Deployment and monitoring;Creating or maintain...,Testing code,Generating content or synthetic data,"AI solutions that are almost right, but not qu...",No. Vibe coding is fine for demos but not prof...,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,I am concerned about the accuracy of the infor...,NaN,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Requirements gathering, big fixing",270000.0,3.0,True,True,True
42,43,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc....",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,35.0,"Developer, mobile","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Personal Project,8.0,3.0,2.0,6.0,7.0,1.0,5.0,4.0,9.0,14.0,NaN,8.0,1.0,6.0,2.0,4.0,9.0,7.0,13.0,14.0,15.0,NaN,Software Development,3.0,4.0,9.0,12.0,13.0,14.0,6.0,2.0,7.0,8.0,1.0,10.0,5.0,15.0,11.0,NaN,No,I have neither consider or transitioned into a...,10.0,10.0,United States of America,USD United States dollar,250000.0,Yes,Bash/Shell (all shells);C;C#;C++;HTML/CSS;Java...,Assembly;Go;Ruby;Rust,NaN,NaN,NaN,NaN,Microsoft SQL Server;MySQL;Oracle;SQLite,Cosmos DB;DuckDB;Dynamodb;IBM DB2;InfluxDB;Mon...,NaN,NaN,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,Yes,AngularJS;ASP.NET;ASP.NET Core;Django;jQuery;N...,Ruby on Rails;Spring Boot,Ruby on Rails,NaN,NaN,Yes,Android Studio;Claude Code;Eclipse;IntelliJ ID...,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Google Gemini,NaN,NaN,NaN,NaN,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Azure Devops;Coda;Doxygen;GitHub;GitLab;Google...,Airtable;Obsidian;Stack Overflow for Teams;Trello,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Company-sponsored forums,Company-sponsored forums,NaN,NaN,Yes,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Alibaba Cloud Qwen models;Amazon Titan models;...,Anthropic: Claude Sonnet,NaN,NaN,Yes,Daily or almost daily,Between 10 and 15 years,A few times per month or weekly,Message Boards;Long-form articles,9.0,NaN,6.0,2.0,4.0,1.0,8.0,7.0,11.0,15.0,NaN,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Very well at handling complex tasks,Documenting code;Generating content or synthet...,NaN,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Debuggi...,Other (write in):,Yes. Use it daily.,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,Language processing;Agent/multi-agent orchestr...,AI agents have increased my productivity.;AI a...,AI agents have improved collaboration within m...,NaN,AI agents have helped me automate repetitive t...,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis;ChromaDB,NaN,Llama Index;Ollama;OpenRouter,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I want to fully understand something;When...,Multiplatform Platform code conversion. Langua...,250000.0,8.0,True,True,True
48,49,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,21.0,"Senior executive (C-suite, VP, etc.)",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,12.0,1.0,10.0,9.0,4.0,2.0,14.0,NaN,14.0,6.0,11.0,10.0,1.0,2.0,5.0,9.0,3.0,15.0,NaN,Fintech,5.0,6.0,7.0,13.0,12.0,8.0,11.0,9.0,10.0,14.0,1.0,3.0,2.0,15.0,4.0,NaN,I'm not sure,I have somewhat considered changing my career ...,10.0,5.0,United Kingdom of Great Britain and Northern I...,GBP Pound sterling,105000.0,Yes,C#;Elixir;HTML/CSS;JavaScript;SQL;TypeScript,C#;Elixir;HTML/CSS;SQL,C#;Elixir;HTML/CSS;SQL,Haskell,NaN,Yes,Cosmos DB;Elasticsearch;Microsoft SQL Server;P...,Cosmos DB;Microsoft SQL Server;PostgreSQL,Cosmos DB;Microsoft SQL Server;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Docker;Go...,Amazon Web Services (AWS);Cloudflare;Docker;Mi...,Amazon Web Services (AWS);Cloudflare;Docker;Mi...,NaN,NaN,Yes,ASP.NET Core;Next.js;Phoenix,ASP.NET Core;Blazor;Phoenix,ASP.NET Core;Phoenix,NaN,Ash,Yes,Aider;Claude Code;Cursor;Jupyter Notebook/Jupy...,Jupyter Notebook/JupyterLab;Neovim;Rider;Visua...,Jupyter Notebook/JupyterLab;Neovim;Rider;Visua...,NaN,NaN,Tailwind CSS 4;Large Language Model;Shadcn/ui,Tailwind CSS 4;Microsoft Fabric;Shadcn/ui,Tailwind CSS 4;Shadcn/ui,NaN,NaN,Windows;MacOS;iOS,MacOS;Ubuntu;Linux (non-WSL),Azure Devops;Confluence;GitHub;Google Workspac...,GitHub;Google Workspace;Lucid (includes Lucidc...,GitHub;Google Workspace;Notion,Whimsical,Whimsical,Stack Overflow;Reddit;Hacker News;GitHub (publ...,Stack Overflow;Discord;Reddit;Hacker News;GitH...,Stack Overflow;Reddit;Hacker News;GitHub (publ...,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet;Gemini (Pro Reasoning...,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",Long-form articles;Coding challenges;Lists of ...,9.0,NaN,10.0,6.0,1.0,2.0,8.0,11.0,14.0,15.0,NaN,"Yes, somewhat",Less than half of the time,"Yes, I use AI tools monthly or infrequently",Unfavorable,Highly distrust,Very poor at handling complex tasks,Writing code;Debugging or fixing code;Learning...,Project planning;Documenting code;Deployment a...,Learning about a codebase;Testing code;Committ...,Generating content or synthetic data,NaN,"AI solutions that are almost right, but not qu...",No,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,My company's IT and/or InfoSec teams have stri...,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"Problem solving and reasoning, unless we get f...",142949.0,7.0,False,True,False

In [573]:
# Дивимось колонку з індустріями: Industry
# Перевіряємо:
# df[['Industry']].unique()
df['Industry'].value_counts(dropna=False)

Industry
Software Development                          16282
NaN                                           15549
Other:                                         2667
Internet, Telecomm or Information Services     1698
Fintech                                        1690
Banking/Financial Services                     1437
Healthcare                                     1397
Manufacturing                                  1315
Government                                     1183
Higher Education                               1167
Retail and Consumer Services                   1053
Transportation, or Supply Chain                 910
Computer Systems Design and Services            894
Media & Advertising Services                    773
Energy                                          742
Insurance                                       434
Name: count, dtype: int64

In [574]:
# Знайдемо найпопулярніші індустрії
top_industries = (
    remote_high_paid_df['Industry']
    .dropna()
    .value_counts()
    .reset_index()
)
top_industries.columns = ['Industry', 'Count']
top_industries

                                      Industry  Count
0                         Software Development   1186
1                                      Fintech    190
2                                   Healthcare    188
3                                       Other:    176
4   Internet, Telecomm or Information Services    138
5                   Banking/Financial Services     88
6                                   Government     78
7                 Media & Advertising Services     75
8                 Retail and Consumer Services     65
9              Transportation, or Supply Chain     63
10        Computer Systems Design and Services     59
11                                   Insurance     46
12                                      Energy     45
13                               Manufacturing     33
14                            Higher Education     30

In [575]:
# Для кращої візуалізації:
top_industries.head(10).style.background_gradient(cmap='Blues')